apiVersion: v1
kind: ConfigMap
metadata:
  name: resource-tree-handler-webservice-config
  labels:
  {{- include "resource-tree-handler.labels" . | nindent 4 }}
data:
  config.yaml: |
    WebServicePort: 8084
