apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "resource-tree-handler.fullname" . }}
  labels:
  {{- include "resource-tree-handler.labels" . | nindent 4 }}
data:
  RESOURCE_TREE_HANDLER_PORT: "{{ .Values.service.port }}"