apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "resource-tree-handler.fullname" . }}-deployment
  labels:
    app: resource-tree-handler
  {{- include "resource-tree-handler.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.webservice.replicaCount }}
  selector:
    matchLabels:
      app: resource-tree-handler
    {{- include "resource-tree-handler.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: resource-tree-handler
      {{- include "resource-tree-handler.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: CONFIG_PATH
          value: {{ quote .Values.webservice.configMountPath }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: "cluster.local"
        image: {{ .Values.webservice.image.repository }}:{{ .Values.webservice.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.webservice.imagePullPolicy }}
        name: webservice
        ports:
        - containerPort: 8084
        resources: {{- toYaml .Values.webservice.resources
          | nindent 10 }}
        {{- with .Values.webservice.volumeMounts }}
        volumeMounts:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      imagePullSecrets: {{- toYaml .Values.imagePullSecrets
          | nindent 6 }}
      serviceAccountName: {{ include "resource-tree-handler.fullname" . }}-secret-viewer
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
