apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "resource-tree-handler.fullname" . }}-secret-reader-role
  labels:
  {{- include "resource-tree-handler.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
